config/routes.rb
require "sidekiq-scheduler/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  root "pages#index"
  get "/search", to: "pages#search"
  get "feeds/pipe"

  resources :movies, only: %i[index show]
  resources :fanza_actresses, only: %i[index show], path: "actresses"
  resources :fanza_items, only: %i[show]
  resources :javlibrary_items, only: %i[show]
  resources :mgstage_items, only: %i[show]
  resources :sod_items, only: %i[show]
  resources :fc2_items, only: %i[show]

  constraints Clearance::Constraints::SignedIn.new { |user| user.is_admin? } do
    resources :movies, only: %i[update destroy]
    resources :fanza_items, only: %i[index destroy update]
    resources :javlibrary_items, only: %i[index destroy]
    resources :javlibrary_pages, only: %i[index show new create]
    resources :mgstage_items, only: %i[index destroy]
    resources :mgstage_pages, only: %i[index show]
    resources :sod_items, only: %i[index destroy]
    resources :sod_pages, only: %i[index show]
    resources :fc2_items, only: %i[index destroy]
    resources :fc2_pages, only: %i[index show]
    resources :feeds, only: %i[index show destroy update]
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all

    @order = params[:order]&.downcase&.to_sym
    case @order
    when :release_date
      @movies = @movies.order(date: :desc, normalized_id: :desc)
    when :date_added
      @movies = @movies.order(id: :desc)
    else
      @order = :title
      @movies = @movies.order(:normalized_id)
    end

    if params[:q]
      @style = params[:style]&.downcase&.to_sym
      case @style
      when :prefix
        @movies = @movies.with_prefix params[:q]
      else
        @style = :fuzzy
        @movies = @movies.fuzzy_match params[:q]
      end
    end
    @movies = @movies.page(params[:page])
  end

  def show
    id = params[:id].upcase
    @movie = Movie.find_by(normalized_id: id)
    @item = @movie&.preferred_item
    unless @item
      @searching = FanzaSearcher.perform_async id if signed_in? or request.format.json?
      @related_movies = Movie.fuzzy_match(id).order(:normalized_id).page(params[:page])
    end

    respond_to do |format|
      format.html {
        if @item && !@movie.is_hidden?
          render
        else
          render :not_found, status: :not_found
        end
      }
      format.json {
        if @item
          render
        elsif @searching
          render json: { err: "processing" }, status: :accepted
        else
          render json: { err: "not_found" }, status: :not_found
        end
      }
    end
  end

  def update
    id = params[:id].upcase
    @movie = Movie.find_by(normalized_id: id)
    @movie.update params.permit(:cover_image_url)
    redirect_to @movie
  end

  def destroy
    id = params[:id].upcase
    @movie = Movie.find_by(normalized_id: id)
    @searching = FanzaSearcher.perform_async id
    redirect_to @movie
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def to_items(movies_or_items)
    case movies_or_items.first
    when Movie
      movies_or_items.reject(&:is_hidden?).map(&:preferred_item)
    else
      movies_or_items.reject { |item| item.movie.is_hidden? }
    end
  end
end

app/views/movies/_cards.html.erb
<% render_pager = local_assigns.fetch(:render_pager, true) %>
<% always_link_to_movie = local_assigns.fetch(:link_to_movie, true) %>

<% if render_pager %>
<%= render partial: "layouts/pager", locals: { items: cards, name: "movie" } %>
<% end %>

<% to_items(cards).in_groups_of(6).each do |group| %>
<div class="movies card-group mb-3">
  <% group.each do |item| %>
  <div class="card">
    <% if item %>
      <% link_dst = (always_link_to_movie || item.preferred? )? item.movie : item %>
      <%= link_to(
        image_tag(item.thumbnail_image_url, class: "card-image-top img-fluid mx-auto d-block"),
        link_dst
      )%>
      <div class="card-body">
        <%= link_to link_dst, class: "card-title" do %>
        <h5>
          <%= item.normalized_id %>
        </h5>
        <h6 class="text-truncate">
          <small>
            <%= item.title %>
          </small>
        </h6>
        <% end %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>
<% end %>

<% if render_pager and cards.present? %>
<%= render partial: "layouts/pager", locals: { items: cards, name: "movie" } %>
<% end %>

app/views/movies/_pager.html.erb
<div class="d-md-flex justify-content-between align-items-center">
  <%= paginate @items, window: 2 %>
  <p>
    <%= page_entries_info @items %>
  </p>
</div>

app/views/movies/_search.html.erb
<%= form_tag search_path, method: :get, class: "form-inline" do %>
<div class="input-group col-md-12">
    <%= text_field_tag("q", nil, class: "form-control") %>
    <%= submit_tag "Search", class: "btn btn-success" %>
</div>
<% end %>

app/views/movies/index.html.erb
<% content_for :title do %>
<%= params[:q] %>
<% end %>

<nav class="card mb-3">
    <div class="card-body">
        <div class="row">
            <%= form_tag movies_path, method: :get, class: "col-md-auto", id: "search" do %>
            <input name="order" type="hidden" value="<%= @order %>" />
            <input name="style" type="hidden" value="<%= @style %>" />
            <div class="input-group">
                <%= text_field_tag("q", params[:q], class: "form-control") %>
                <%= submit_tag "Search", class: "btn btn-success" %>
            </div>
            <% end %>

            <div class="col-md-auto btn-group">
                <button type="button" class="btn btn-outline-dark" disabled>
                    Style
                </button>
                <% %i[fuzzy prefix].each do |style| %>
                <%= link_to(
                    style.to_s.titleize,
                    request.params.except("page").merge(style: style),
                    class: (@style==style ? "btn btn-primary active" : "btn btn-secondary"),
                    role: "button",
                ) %>
                <% end %>
            </div>

            <div class="col-md-auto btn-group">
                <button type="button" class="btn btn-outline-dark" disabled>
                    Sort by
                </button>
                <% (signed_in_as_admin? ? %i[title release_date date_added] : %i[title release_date]).each do |opt| %>
                <%= link_to(
                    opt.to_s.titleize,
                    request.params.except("page").merge(order: opt),
                    class: (@order==opt ? "btn btn-primary active" : "btn btn-secondary"),
                    role: "button",
                ) %>
                <% end %>
            </div>
        </div>
    </div>
</nav>

<%= render partial: "movies/cards", object: @movies %>

app/views/movies/items.html.erb
<%= render partial: "movies/cards", object: @items, locals: { link_to_movie: false } %>

app/views/movies/not_found.html.erb
<% if @searching %>

<div class="jumbotron">
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-primary mb-3" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <strong>Loading in background, try come back later.</strong>
    </div>
</div>
<% else %>

<div class="jumbotron d-flex justify-content-center">
    <h1>Not found <small class="text-muted">yet</small></h1>
</div>

<% end %>

<%if @related_movies.present? %>

<h2 class="mb-3">You might be looking for</h2>
<%= render partial: "movies/cards", object: @related_movies %>

<% end %>

app/views/movies/show.html.erb
<% content_for :title do %>
<%= @item.normalized_id %>
<% end %>

<button class="btn text-start" data-clipboard-text="<%= @item.normalized_id %>">
  <h1>
    <span><%= @item.normalized_id %></span>
    <span><%= @item.title %></span>
  </h1>
</button>
<div class="ms-2">
  <% if signed_in_as_admin? %>
  <div class="d-inline-block">
    <%= button_to "Re-Search", @movie, method: :delete, class: "btn btn-danger d-inline" %>
  </div>
  <div class="d-inline-block">
    <%= button_to "Re-Derive", @item, method: :delete, class: "btn btn-warning" %>
  </div>
  <% if @item.is_a? FanzaItem %>
  <div class="d-inline-block">
    <%= button_to "Promote", fanza_item_path(@item, priority_inc: 1), method: :put, class: "btn btn-success" %>
  </div>
  <div class="d-inline-block">
    <%= button_to "Demote", fanza_item_path(@item, priority_inc: -1), method: :put, class: "btn btn-danger" %>
  </div>
  <% end %>
  <% end %>
</div>

<div class="row mt-3 mb-3">
  <div class="col-md-8">
    <%= image_tag @item.cover_image_url, class: "img-fluid" %>

    <% if signed_in_as_admin? %>
    <div class="card border-danger mt-3 mb-3">
      <div class="card-body pt-3 pb-2">
        <dl class="row mb-0">
          <dt class="col-md-3">Movie Page</dt>
          <dd class="col-md-9"><%= link_to movie_path(@item.normalized_id), movie_path(@item.normalized_id) %></dd>
          <dt class="col-md-3">Item Page</dt>
          <dd class="col-md-9"><%= link_to url_for(@item), @item %></dd>
          <dt class="col-md-3">Data Source</dt>
          <dd class="col-md-9 text-truncate"><%= link_to @item.url, @item.url %></dd>
          <dt class="col-md-3">Date Added</dt>
          <dd class="col-md-9"><%= time_tag @item.created_at %></dd>
          <% if @item.has_attribute? :priority %>
          <dt class="col-md-3">Priority</dt>
          <dd class="col-md-9"><%= @item.priority %></dd>
          <% end %>
          <% if @movie %>
          <dt class="col-md-3">Cover Image</dt>
          <dd class="col-md-9">
            <%= form_tag @movie, method: :put, class: "row", id: "update" do %>
              <div class="col-md-12">
                <div class="input-group">
                  <%= text_field_tag "cover_image_url", @movie.cover_image_url, class: "form-control" %>
                  <div class="input-group-append">
                    <%= submit_tag "Update" , class: "btn btn-success" %>
                  </div>
                </div>
              </div>
            <% end %>
          </dd>
          <% end %>
        </dl>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <dl>
      <dt>Thumbnail Image</dt>
      <dd><%= image_tag @item.thumbnail_image_url, class: "img-fluid" %></dd>

      <dt>Release Date</dt>
      <dd><%= @item.date.to_date %></dd>

      <% %i[directors genres labels makers].each do |attr| %>
      <% if @item.send(attr).present? %>
      <dt><%= attr.to_s.humanize %></dt>
      <dd>
        <ul class="list-inline">
          <% @item.send(attr).each do |elem| %>
          <li class="list-inline-item">
            <%= elem %>
          </li>
          <% end %>
        </ul>
      </dd>
      <% end %>
      <% end %>

      <% if @item.volume.present? %>
      <dt>Volume</dt>
      <dd><%= (@item.volume / 60) %> minutes</dd>
      <% end %>

      <% if @item.review.present? %>
      <dt>User Rating</dt>
      <dd><%= "%.1f" % @item.review %></dd>
      <% end %>
      <dt>
        External Links
      </dt>
      <dd>
        <ul class="list-inline external-links">
          <li class="list-inline-item">
            <%= link_to @item.url do %>
            <%= image_tag @item.logo_url, class: "img-fluid", referrerpolicy: "no-referrer" %>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to "https://www.javbus.com/search/#{@item.normalized_id}", rel: "noreferrer" do %>
            <%= image_tag "javbus.png", class: "img-fluid javbus" %>
            <% end %>
          </li>
        </ul>
      </dd>
    </dl>
  </div>
</div>

<dl>
  <% if @item.description.present? %>
  <dt>Description</dt>
  <dd><%= @item.description %></dd>
  <% end %>

  <% if @item.actresses.present? %>
  <dt>Actresses</dt>
  <dd>
    <%= render partial: "fanza_actresses/cards", object: @item.actresses %>
  </dd>
  <% end %>

  <% if @item.sample_image_urls.present? %>
  <dt>Sample Images</dt>
  <dd>
    <div class="card mt-3 mb-3">
      <div class="card-body pt-3 pb-2">
        <div id="sample-images">
          <% @item.sample_image_urls.each do |img| %>
            <%= link_to img, target: "_blank" do %>
              <% image_tag img %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </dd>
  <% end %>

  <% if @item.movie.items.count > 1 %>
  <dt class="mb-3">Other versions</dt>
  <dd>
    <%= render(
      partial: "movies/cards",
      object: Kaminari.paginate_array(@item.movie.items.excluding(@item)).page(1).per(20),
      locals: { render_pager: false, link_to_movie: false }
    )%>
  </dd>
  <% end %>
</dl>