config/routes.rb
require "sidekiq-scheduler/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  root "pages#index"
  get "/search", to: "pages#search"
  get "feeds/pipe"

  resources :movies, only: %i[index show]
  resources :fanza_actresses, only: %i[index show], path: "actresses"
  resources :fanza_items, only: %i[show]
  resources :javlibrary_items, only: %i[show]
  resources :mgstage_items, only: %i[show]
  resources :sod_items, only: %i[show]
  resources :fc2_items, only: %i[show]

  constraints Clearance::Constraints::SignedIn.new { |user| user.is_admin? } do
    resources :movies, only: %i[update destroy]
    resources :fanza_items, only: %i[index destroy update]
    resources :javlibrary_items, only: %i[index destroy]
    resources :javlibrary_pages, only: %i[index show new create]
    resources :mgstage_items, only: %i[index destroy]
    resources :mgstage_pages, only: %i[index show]
    resources :sod_items, only: %i[index destroy]
    resources :sod_pages, only: %i[index show]
    resources :fc2_items, only: %i[index destroy]
    resources :fc2_pages, only: %i[index show]
    resources :feeds, only: %i[index show destroy update]
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/layouts/_pager.html.erb
<div class="d-md-flex justify-content-between align-items-center">
  <%= paginate items, window: 2 %>
  <div>
    <p>
      <%= page_entries_info items, entry_name: name %>
      <% if !items.is_a?(Kaminari::PaginatableArray) and items.exists? and items.has_attribute? :date %>
        <br/>
        <small class="text-secondary">
        Released between
        <%= items.except(:limit, :offset).minimum(:date).to_date %> and
        <%= items.except(:limit, :offset).maximum(:date).to_date %>
        </small>
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>
    <% if content_for?(:title) %>
    <%= yield(:title) %> | LibreFanza
    <% else %>
    LibreFanza
    <% end %>
  </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js"></script>
  <script>
    new ClipboardJS('.btn');
  </script>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
    <a class="navbar-brand" href="/">LibreFanza</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Movies", movies_path, class: "nav-link" %>
        </li>

        <% if signed_in_as_admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Fanza Items", fanza_items_path, class: "dropdown-item" %></li>
            <li><%= link_to "FC2 Items", fc2_items_path, class: "dropdown-item" %></li>
            <li><%= link_to "FC2 Pages", fc2_pages_path, class: "dropdown-item" %></li>
            <li><%= link_to "Javlibrary Items", javlibrary_items_path, class: "dropdown-item" %></li>
            <li><%= link_to "Javlibrary Pages", javlibrary_pages_path, class: "dropdown-item" %></li>
            <li><%= link_to "Mgstage Items", mgstage_items_path, class: "dropdown-item" %></li>
            <li><%= link_to "Mgstage Pages", mgstage_pages_path, class: "dropdown-item" %></li>
            <li><%= link_to "SOD Items", sod_items_path, class: "dropdown-item" %></li>
            <li><%= link_to "SOD Pages", sod_pages_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Actresses", fanza_actresses_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <%= render "movies/search" %>
        <% if signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu">
            <% if signed_in_as_admin? %>
            <li><%= link_to "Sidekiq", sidekiq_web_path, class: "dropdown-item" %></li>
            <li><%= link_to "Feeds", feeds_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"/></li>
            <% end %>
            <li><%= link_to (t ".sign_out"), sign_out_path, data: { "turbo-method": :delete }, class: "dropdown-item" %></li>
          </ul>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to (t ".sign_in"), sign_in_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
    </div>
  </nav>

  <main role="main" class="container">
    <%= yield %>
  </main>
</body>

<footer class="footer">
  <div class="container text-center">
    <a href="https://github.com/libredmm/librefanza">
      <img src="https://img.shields.io/static/v1?label=libredmm%2Flibrefanza&message=admin%40libredmm.com&color=blue&logo=github" />
    </a>
  </div>
</footer>

</html>